export interface Shipment {
    id: number,
    company: string,
    price: number,
    startDate: string,
    startHour: string,
    startCity: string,
    startAirport: string,
    endDate: string,
    endHour: string,
    endCity: string,
    endAirport: string,
    weightLimit: number,
    carrierId: number,
    carrierFirstName: string,
    carrierLastName: string,
    carrierAge: number,
    carrierExperienceYear: number,
    carrierImg: string,
    carrierRate: number
}

export const shipments = [
    {
        id: 1,
        company: 'Air France',
        price: 50.25,
        startDate: 'Vendredi 2 avril 2021',
        startHour: '11h00 GMT',
        startCity: 'Paris',
        startAirport: 'Aéroport Charles de Gaulle',
        endDate: 'Vendredi 2 avril 2021',
        endHour: '22h00 GMT',
        endCity: 'Abidjan',
        endAirport: 'Aéroport Felix Houphouët Boigny',
        weightLimit: 45,
        carrierId: 1,
        carrierFirstName: 'Fulgence',
        carrierLastName: 'Kouakou',
        carrierAge: 55,
        carrierExperienceYear: 25,
        carrierImg: '../../assets/img/user-1.jpg',
        carrierRate: 4.5
    },
    {
        id: 2,
        company: 'Air Royal MAROC',
        price: 51.25,
        startDate: 'Samedi 3 avril 2021',
        startHour: '16h00 GMT',
        startCity: 'Paris',
        startAirport: 'Aéroport Charles de Gaulle',
        endDate: 'Dimanche 4 avril 2021',
        endHour: '22h00 GMT',
        endCity: 'Abidjan',
        endAirport: 'Aéroport Felix Houphouët Boigny',
        weightLimit: 60,
        carrierId: 2,
        carrierFirstName: 'Edwin',
        carrierLastName: 'Bossard',
        carrierAge: 50,
        carrierExperienceYear: 10,
        carrierImg: '../../assets/img/user-2.jpg',
        carrierRate: 3.7
    }
];